name: shared_preferences
description: Flutter plugin for reading and writing simple key-value pairs.
  Wraps NSUserDefaults on iOS and SharedPreferences on Android.
repository: https://github.com/suzukishingo/packages/tree/main/packages/shared_preferences/shared_preferences
version: 2.2.1

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: shared_preferences_android
      ios:
        default_package: shared_preferences_foundation
      linux:
        default_package: shared_preferences_linux
      macos:
        default_package: shared_preferences_foundation
      web:
        default_package: shared_preferences_web
      windows:
        default_package: shared_preferences_windows

dependencies:
  flutter:
    sdk: flutter
  shared_preferences_android:
    git:
      url: git@github.com:suzukishingo/packages.git
      path: packages/shared_preferences/shared_preferences_android
  shared_preferences_foundation: ^2.2.0
  shared_preferences_linux: ^2.2.0
  shared_preferences_platform_interface: ^2.3.0
  shared_preferences_web: ^2.1.0
  shared_preferences_windows: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

topics:
  - persistence
  - shared-preferences
  - storage
